/*
   This file was generated automatically by the Mojo IDE version B1.3.4.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module eightbitCMPEQ_10 (
    input z,
    output reg [7:0] out
  );
  
  
  
  reg [7:0] x;
  
  integer i;
  
  always @* begin
    x[0+0-:1] = z;
    for (i = 1'h1; i < 4'h8; i = i + 1) begin
      x[(i)*1+0-:1] = 1'h0;
    end
    out = x;
  end
endmodule
