/*
   This file was generated automatically by the Mojo IDE version B1.3.4.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module eightbitnota_23 (
    input [7:0] a,
    output reg [7:0] out
  );
  
  
  
  always @* begin
    out = ~a;
  end
endmodule
