/*
   This file was generated automatically by the Mojo IDE version B1.3.4.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module eightbitadder_1 (
    input [7:0] a,
    input [7:0] b,
    output reg [7:0] out,
    output reg z,
    output reg v,
    output reg n
  );
  
  
  
  reg [7:0] x;
  
  reg [8:0] y;
  
  always @* begin
    x = a + b;
    y = a + b;
    out = x;
    if (x == 1'h0) begin
      z = 1'h1;
    end else begin
      z = 1'h0;
    end
    v = y[8+0-:1];
    n = x[7+0-:1];
  end
endmodule
