/*
   This file was generated automatically by the Mojo IDE version B1.3.4.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module eightbitdotproduct_22 (
    input [7:0] a,
    input [7:0] b,
    output reg [7:0] out
  );
  
  
  
  integer count;
  
  integer i;
  
  always @* begin
    for (i = 1'h0; i < 4'h8; i = i + 1) begin
      count = count + a[(i)*1+0-:1] * b[(i)*1+0-:1];
    end
    for (i = 1'h0; i < 4'h8; i = i + 1) begin
      out[(i)*1+0-:1] = count - count / 2'h2 * 2'h2;
      count = count / 2'h2;
    end
  end
endmodule
